// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// promise_task.cpp
void asyncFib(cpp11::function resolve, cpp11::function reject, double x);
extern "C" SEXP _promises_asyncFib(SEXP resolve, SEXP reject, SEXP x) {
  BEGIN_CPP11
    asyncFib(cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(resolve), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(reject), cpp11::as_cpp<cpp11::decay_t<double>>(x));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_promises_asyncFib", (DL_FUNC) &_promises_asyncFib, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_promises(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
